// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoNYx5fDRR9aVJV5V1jE4LXQzXWez0YY8',
    appId: '1:251728636063:web:58edad62f01abbc1915aaa',
    messagingSenderId: '251728636063',
    projectId: 'qrcode-97873',
    authDomain: 'qrcode-97873.firebaseapp.com',
    storageBucket: 'qrcode-97873.appspot.com',
    measurementId: 'G-PYC0PPYT8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7_1n14skrHE4bLvJjia5eBjiNgr8Xqm8',
    appId: '1:251728636063:android:9e0c24ed79051b86915aaa',
    messagingSenderId: '251728636063',
    projectId: 'qrcode-97873',
    storageBucket: 'qrcode-97873.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHoeO_G8I9VDi2xOLQEWPfcJ48F0VFBng',
    appId: '1:251728636063:ios:776a43eff0bbbbf7915aaa',
    messagingSenderId: '251728636063',
    projectId: 'qrcode-97873',
    storageBucket: 'qrcode-97873.appspot.com',
    iosBundleId: 'com.FIKRI140702.qrCode',
  );
}
